language: python
python:
- '2.7'
install: pip install -r requirements/test.txt
script: python manage.py test
deploy:
  provider: pypi
  user: edx
  password:
    secure: 1qOq37zLf1GDkUSf3e4q08pV5OVJ57JIesDd5t/qZ6D0EUQmnIYbLldWBWV9je1jeYdUTmFE20b0vvqCZgHICroX6DJat0dkG/6pncIeLodl64FQngXRDYe7HZpSrLuXavn1x48yzF25lY5WwplOm7kspMVTOcXEmIjaGiywDJByzy7uKAdQDHpc8IOc1zxhGE2ygNBThiozpht3w7Xa91vAKlv4w0TeDzxtOvBzPIqRiocnEper1T3S4E95XUtrp2fXlBaBCdsjbteM0BFeLK0UmCuQCrFd/xT2A0dop0GMSvC2krpfvbD3NDWOhTU6v/5p20ufrbTK0Gpb2LzuGCFJCzmMMXTIBjsZ/z2s8p5q9m/exx9eLBGhIfOV9YY1xqKoVw2IX7xRMHAPJtQmaVw+968aasOJLF6QOZoUiUe1fr6x6KuhXa0V7iJeH0psg7oySAL5Y09MEXCbexRvjcfoNXaT9lK7dQ5Py8Tb2r7COBiN1lGTY2FEA3HRn4d5Q44Ngub6sg58U6S07C5CFZjMosxKN91gHRVfvhQRVH7egjInBSO/2HrYIhAN79dlTwqWNFeII7Vx11QN+8ePdyzKtnL917/atyZDkg29wuHe+lCL0LqYVmg8YwE9k/r6uTGMaoRXjVghV7ketJtDBj39f8n1BilrpV28b/i9zhg=
  distributions: sdist bdist_wheel
  on:
    tags: true
